app/models.py
# -*- coding: utf-8 -*-
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from . import login_manager


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    permission = db.Column(db.Integer)

    def __repr__(self):
        return '<Role %r>' % self.name


class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True)
    email = db.Column(db.String(64), unique=True)
    password_hash = db.Column(db.String(128))
    signup_time = db.Column(db.DateTime())
    login_time = db.Column(db.DateTime())

    @property
    def password(self):
        raise AttributeError('Password is not readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<User %r>' % self.username

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return True

    def get_id(self):
        return unicode(self.id)


@login_manager.user_loader
def load_user(user_id):
    """
    Flasg_Login用于标识加载用户
    :param user_id:
    :return:
    """
    return User.query.get(int(user_id))


class SubsOperation(db.Model):
    __name__ == 'subsoperation'

    id = db.Column(db.Integer, primary_key=True)
    product_code = db.Column(db.String(21))
    user_msisdn = db.Column(db.String(48))
    pay_user = db.Column(db.String(48))
    operation = db.Column(db.String(2))
    status = db.Column(db.String(2))
    operation_mode = db.Column(db.Integer)
    operation_date = db.Column(db.DateTime)
    effictive_date = db.Column(db.DateTime)
    device_type = db.Column(db.Integer)
    device_id = db.Column(db.String(6))

    def __repr__(self):
        return '<SubsOperation %r>' % self.id

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from main import bp_main
    app.register_blueprint(bp_main, url_prefix='/')

    from api import bp_api
    app.register_blueprint(bp_api, url_prefix='/api')

    from auth import bp_auth
    app.register_blueprint(bp_auth, url_prefix='/auth')

    return app

app/api/__init__.py
from flask import Blueprint

bp_api = Blueprint('api', __name__)

from . import views

app/api/views.py
from flask import Flask, render_template, redirect, request, url_for, flash
from . import bp_api
from .. import db
from ..models import SubsOperation

@bp_api.route('/')
def index():
    print '__name__', __name__
    return render_template('api/index.html', subtitle='API::')


@bp_api.route('/aqi')
def aqi():
    print '__name__', __name__
    return render_template('api/aqi.html', subtitle='AQI Stats')


@bp_api.route('/pi')
def pi():
    print '__name__', __name__
    return render_template('api/pi.html', subtitle='RaspberryPi')


@bp_api.route('/show')
def show():
    dat = SubsOperation.query.all()
    print SubsOperation.query.count()

    return render_template('api/show.html', table=dat)

app/main/__init__.py
from flask import Blueprint


bp_main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import Flask, render_template, redirect, request, url_for, flash
from . import bp_main


@bp_main.route('/')
def index():
    # print '__name__', __name__
    return render_template('main/index.html')

app/wx/__init__.py
from flask import Blueprint

bp_wx = Blueprint('wx', __name__)

from . import views

app/wx/views.py
from flask import Flask, render_template, redirect, request, url_for, flash
from . import bp_wx


@bp_wx.route('/')
def index():
    print '__name__', __name__
    return render_template('api/index.html', subtitle='API::')


@bp_wx.route('/aqi')
def aqi():
    print '__name__', __name__
    return render_template('api/aqi.html', subtitle='AQI Stats')


@bp_wx.route('/pi')
def pi():
    print '__name__', __name__
    return render_template('api/pi.html', subtitle='RaspberryPi')


# import xxx as wx_parse
# import zzzz as wx_reply
#
#
# def wxmsg_process(xmlreq):
#     dat = wx_parse.parse_xml(xmlreq)
#     if not isinstance(dat, wx_parse.Msg):
#         print 'unsuported'
#         return wx_reply.Msg.send()
#
#     toUserName = dat.ToUserName
#     fromUserName = dat.FromUserName
#
#     if dat.MsgType.lower == 'text':
#         content = 'content...'
#         reply = wx_reply.TextMsg(toUserName, fromUserName, content)
#         return reply.send()
#     elif dat.MsgType.lower == 'image':
#         mediaId = dat.MediaId
#         reply = wx_reply.ImageMsg(toUserName, fromUserName, mediaId)
#         return reply.send()

app/templates/_macro.html
{% macro form_field(field) %}
    {{ field(placeholder=field.label.text) }}
{% endmacro %}


{% macro pagination_widget(pagination) %}
{% endmacro %}


{% macro echarts_body() %}
    <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
    <div id="main" style="height:400px;width: 600px"></div>
    <!-- ECharts单文件引入 -->
{#    <script src="http://echarts.baidu.com/build/dist/echarts.js"></script>#}
    <script src="{{ url_for('static', filename='echarts.js') }}"></script>


    <script type="text/javascript">
        // 路径配置
        require.config({
            paths: {
                echarts: './static'
{#                echarts: 'http://echarts.baidu.com/build/dist'#}
            }
        });

        // 使用
        require(
            [
                'echarts',
                'echarts/chart/bar' // 使用柱状图就加载bar模块，按需加载
            ],
            function (ec) {
                // 基于准备好的dom，初始化echarts图表
                var myChart = ec.init(document.getElementById('main'));

                var option = {
                    tooltip: {
                        show: true
                    },
                    legend: {
                        data:['销量']
                    },
                    xAxis : [
                        {
                            type : 'category',
                            data : ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
                        }
                    ],
                    yAxis : [
                        {
                            type : 'value'
                        }
                    ],
                    series : [
                        {
                            "name":"销量",
                            "type":"bar",
                            "data":[5, 20, 40, 10, 10, 20]
                        }
                    ]
                };

                // 为echarts对象加载数据
                myChart.setOption(option);
            }
        );
    </script>
{% endmacro %}

app/templates/a.html
{% extends "base.html"%}

{% block content %} <!--具体内容-->
    <div class="container">
     <div class="row"></div>
         <div class="row">
        {# <#-- col-md-4表示合并4列，col-md-offset-4表示偏移4列 sm意思相同 --#>#}
             <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
                 <div class="page-header">
                 <h1>欢迎您登陆</h1>
                 </div>

                 {% for message in get_flashed_messages() %}
                     <div class="alert alert-warning">
                     <button type="button" class="close" data-dismiss="alter">×</button>
                     {{message}}
                     </div>
                 {% endfor %}

                 <form method="post">
                     <div class="form-group">
                     <label for="username">用户名</label>
                     <input type="text" class="form-control" name="username" id="username" placeholder="请输入用户名">
                     </div>
                     <div class="form-group">
                     <label for="passworld">密码</label>
                     <input type="password" class="form-control" name="password" id="passworld" placeholder="请输入密码">
                     </div>
                     <button type="submit" class="btn btn-default">登录</button>
                 </form>
             </div>
         </div>
    </div>
{% endblock %}

app/templates/api/aqi.html
{% extends "base.html" %}

{% block title %}SoloDisplay - {{subtitle}}{% endblock %}

{% block page_content %}
    <h2>This is Aqi</h2>

<table border="1">
<tr>
  <td>
   <p>这是一个段落。</p>
   <p>这是另一个段落。</p>
  </td>
  <td>这个单元包含一个表格：
   <table border="1">
   <tr>
     <td>A</td>
     <td>B</td>
   </tr>
   <tr>
     <td>C</td>
     <td>D</td>
   </tr>
   </table>
  </td>
</tr>
<tr>
  <td>这个单元包含一个列表：
   <ul>
    <li>苹果</li>
    <li>香蕉</li>
    <li>菠萝</li>
   </ul>
  </td>
  <td>HELLO</td>
</tr>
</table>
{% endblock %}}

app/templates/api/index.html
{% extends "base.html" %}

{% block title %}SoloDisplay - {{subtitle}}{% endblock %}

{% block page_content %}
    <h1>This is API Index</h1>
    <div>
        <button type="button" class="btn btn-default" aria-label="Left Align">
  <span class="glyphicon glyphicon-hd-video" aria-hidden="true"></span>
</button>

<button type="button" class="btn btn-default">
  <span class="glyphicon glyphicon-star" aria-hidden="true"></span> Star
</button>

    </div>

    <div>
    <table class="table table-condensed">
        <tr>
          <td>100</td>
          <td>200</td>
          <td>300</td>
        </tr>
        <tr>
          <td>400</td>
          <td>500</td>
          <td>600</td>
        </tr>
    </table>
    </div>
{% endblock %}}

app/templates/api/pi.html
{% extends "base.html" %}

{% block title %}SoloDisplay - {{subtitle}}{% endblock %}

{% block page_content %}
<div class="jumbotron">
    <h1>春晓</h1>
    <p align="center">
    春眠不觉晓，<br>
    处处闻啼鸟。<br>
    夜来风雨声，<br>
    花落知多少。<br>
    </p>
{#  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>#}
</div>
</div>
    <div>
        <p>注意，浏览器忽略了源代码中的排版（省略了多余的空格和换行）。</p>
    </div>
{% endblock %}}

app/templates/api/show.html
{% extends "base.html" %}

{% block title %}SoloDisplay - {{subtitle}}{% endblock %}

{% block page_content %}
<div>
    <table class="table table-condensed">
        <tr>
            <th>ID</th>
            <th>MSISDN</th>
            <th>PRODUCT</th>
            <th>OPERATION DATE</th>
            <th>EFFECTIVE DATE</th>
            <th>OPERATION</th>
            <th>DEVICE TYPE</th>
            <th>DEVICE ID</th>
        </tr>
        {% for tb in table %}
        <tr>
            <td>{{ tb.id }}</td>
            <td>{{ tb.user_msisdn }}</td>
            <td>{{ tb.product_code }}</td>
            <td>{{ tb.operation_date }}</td>
            <td>{{ tb.effictive_date }}</td>
            <td>{{ tb.operation }}</td>
            <td>{{ tb.device_type }}</td>
            <td>{{ tb.device_id }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}}

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">SoloDispaly</a>
            <!--<img alt="Brand" src="放在上一行中">-->
        </div>

        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                <li><a href="#">Link1</a></li>
{#                下拉#}
                <li class="dropdown">
                    <a href="{{ url_for('api.index') }}" class="dropdown-toggle"
                       data-toggle="dropdown" role="button"
                       aria-haspopup="true" aria-expanded="false">API接口
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('api.index') }}">API接口使用说明</a></li>
                        <li><a href="{{ url_for('api.aqi') }}">AQI采集分析</a></li>
                        <li><a href="{{ url_for('api.pi') }}">RaspberryPi监控</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{{ url_for('api.show') }}">数据查询展示</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                <li><a href="#">Link2</a></li>
                </li>
            </ul>
{#            右导航#}
            <ul class="nav navbar-nav navbar-right">
{#                这里和书上不一样，书上为is_authenticated()。实际不应该有()#}
                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                    <button type="button" class="btn btn-primary navbar-btn">Sign out</button>
                    <button class="btn btn-primary" data-toggle="modal" data-target="#modalLogout">Logout</button>
                {% else %}
                    <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                    <button type="button" class="btn btn-primary navbar-btn">Sign in</button>
                    <button class="btn btn-primary" data-toggle="modal" data-target="#modalLogin">Login</button>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div>
    {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

app/templates/ec.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <title>ECharts</title>
</head>
<body>
<div>
<button id="nextPage">Next Page</button>
<script>function clickNextPage(){
        window.location.reload("http://www.baidu.com");}</script>
</div>

    <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
    <div id="main" style="height:400px"></div>
    <!-- ECharts单文件引入 -->
    <script src="http://echarts.baidu.com/build/dist/echarts.js"></script>
    <script type="text/javascript">
        // 路径配置
        require.config({
            paths: {
                echarts: 'http://echarts.baidu.com/build/dist'
            }
        });

        // 使用
        require(
            [
                'echarts',
                'echarts/chart/bar' // 使用柱状图就加载bar模块，按需加载
            ],
            function (ec) {
                // 基于准备好的dom，初始化echarts图表
                var myChart = ec.init(document.getElementById('main'));

                var option = {
                    tooltip: {
                        show: true
                    },
                    legend: {
                        data:['销量']
                    },
                    xAxis : [
                        {
                            type : 'category',
                            data : ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
                        }
                    ],
                    yAxis : [
                        {
                            type : 'value'
                        }
                    ],
                    series : [
                        {
                            "name":"销量",
                            "type":"bar",
                            "data":[5, 20, 40, 10, 10, 20]
                        }
                    ]
                };

                // 为echarts对象加载数据
                myChart.setOption(option);
            }
        );
    </script>
</body>

app/templates/main/index.html
{% extends "base.html" %}
{#{% from "auth/_login_form_helpers.html" import echarts_body %}#}
{% from "_macro.html" import echarts_body %}

{% block title %}SoloDisplay{% endblock %}

{% block page_content %}
<h1>This is Main Index</h1>
<h2>This is Main Index</h2>
    <div>
        {{ echarts_body() }}
    </div>
{% endblock %}}

app/templates/modal.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"> 
	<title>Bootstrap 实例 - 模态框（Modal）插件</title>
	<link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<h2>创建模态框（Modal）</h2>
<!-- 按钮触发模态框 -->
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
	开始演示模态框
</button>
<!-- 模态框（Modal） -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
{#			<div class="modal-header">#}
{#				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">#}
{#					&times;#}
{#				</button>#}
{#				<h4 class="modal-title" id="myModalLabel">#}
{#					模态框（Modal）标题#}
{#				</h4>#}
{#			</div>#}
{#			<div class="modal-body">#}
{#				在这里添加一些文本#}
{#			</div>#}
{#			<div class="modal-footer">#}
{#				<button type="button" class="btn btn-default" data-dismiss="modal">关闭#}
{#				</button>#}
{#				<button type="button" class="btn btn-primary">#}
{#					提交更改#}
{#				</button>#}
{#			</div>#}
            <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
                 <div class="page-header">
                    <h1>登陆</h1>
                 </div>

                 {% for message in get_flashed_messages() %}
                     <div class="alert alert-warning">
                         <button type="button" class="close" data-dismiss="alert">&times;</button>
                         {{ message }}
                     </div>
                 {% endfor %}

                 <div class="col-md-4">
                     {{ wtf.quick_form(form) }}
                     <br>
                     <div>
                     <p><a href="{{ url_for("auth.login") }}">忘记密码？</a></p>
                     <p><a href="{{ url_for("auth.register") }}">不是我们的用户？</a></p>
                     </div>
                 </div>
             </div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal -->
</div>
</body>
</html>

app/templates/test_show.html
{% extends "base.html" %}

{% block title %}SoloDispaly - Test Show{% endblock %}

{% block page_content %}
<h2>{{ detail }}</h2>
{% endblock %}}